=head1 NAME

eBay::API::XML::Call::GetItemRecommendations::GetItemRecommendationsResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetItemRecommendations::GetItemRecommendationsResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

GetItemRecommendations returns recommended changes or opportunities for improvement
related to listing data that was passed in the request.
This call supports batch requests. That is, it can retrieve recommendations for multiple
items at once.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setGetRecommendationsResponseContainer()

Specifies recommended changes or opportunities for improving the data of a single item.
If multiple items were processed, a separate GetRecommendationsResponseContainer
is returned for each item. Each container includes a user-defined correlation ID
to help you match items in the request to recommendations in the response.

#    Argument: reference to an array  
                      of 'ns:GetRecommendationsResponseContainerType'


=cut

=head2 getGetRecommendationsResponseContainer()

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:GetRecommendationsResponseContainerType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

