=head1 NAME

eBay::API::XML::Call::GetWantItNowPost::GetWantItNowPostRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetWantItNowPost::GetWantItNowPostRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Retrieves data for a specific, active Want It Now post identified by a post ID.
The response includes the following fields: CategoryID, Description, PostID,
Site, StartTime, ResponseCount, and Title. Although GetWantItNowSearchResults
returns most of this information, only GetWantItNowPost returns Description for
a post.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setPostID()

Specifies the post ID that uniquely identifies the Want It Now post for
which to retrieve the data. PostID is a required input. PostID is unique
across all eBay sites.

  RequiredInput: Yes
#    Argument: 'ns:ItemIDType'


=cut

=head2 getPostID()

#    Returns: 'ns:ItemIDType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

