=head1 NAME

eBay::API::XML::Call::GetOrderTransactions::GetOrderTransactionsRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetOrderTransactions::GetOrderTransactionsRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Retrieves information about one or more orders or one or more transactions
(or both). If you have both orderIDs and itemIDs/transactionIDs, you may find
this "combined call" more convenient than calling GetOrders and GetItemTransactions
separately.
Note that every transaction is nested within an Order
node, even if the transaction does not belong to an order.
<br>
<br>
Note: OrderID is not returned when the GetOrderTransactions request includes
ItemTransactionID, even if the transaction is part of an order.
To get the OrderID for a transaction, call GetItemTransaction with
IncludeContainingOrder = true.
<br>
<br>
Does not retrieve Express orders, even when the explicit Express OrderID found on the eBay Express site is included in the request.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setIncludeFinalValueFees()

Indicates whether to include the final value fee in the 
following field of the response: Transaction.FinalValueFee.
For most listing types, the fee is returned in Transaction.FinalValueFee.
For Dutch auctions that end with bids (not Buy It Now purchases), the fee
is returned in the following field 
regardless of what you specify in the IncludeFinalValueFees field: 
Item.SellingStatus.FinalValueFee.
The Final Value Fee for FixedPriceItem, StoresFixedPrice, and Buy It Now
Dutch listing types is returned on a transaction-by-transaction basis.
For all other listing types, including Chinese and Dutch (not Buy It Now
purchases), the Final Value Fee is returned when the listing status is
Completed.

  RequiredInput: No
#    Argument: 'xs:boolean'


=cut

=head2 isIncludeFinalValueFees()

#    Returns: 'xs:boolean'


=cut

=head2 setItemTransactionIDArray()

An array of ItemTransactionIDs.

  RequiredInput: Conditionally
#    Argument: 'ns:ItemTransactionIDArrayType'


=cut

=head2 getItemTransactionIDArray()

#    Returns: 'ns:ItemTransactionIDArrayType'


=cut

=head2 setOrderIDArray()

An array of OrderIDs. You can specify, at most, twenty OrderIDs.

  RequiredInput: Conditionally
#    Argument: 'ns:OrderIDArrayType'


=cut

=head2 getOrderIDArray()

#    Returns: 'ns:OrderIDArrayType'


=cut

=head2 setPlatform()

Name of the eBay co-branded site upon which the transaction was made.
This will serve as a filter for the transactions to get emitted in the response.

  RequiredInput: No
#    Argument: 'ns:TransactionPlatformCodeType'


=cut

=head2 getPlatform()

#    Returns: 'ns:TransactionPlatformCodeType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

