=head1 NAME

eBay::API::XML::Call::VeROReportItems::VeROReportItemsRequestType

=head1 DESCRIPTION

Reports items that allegedly infringe your copyright, trademark, or other 
intellectual property rights. You can report one or more items at a time with this 
call. You must be a member of the Verified Rights Owner (VeRO) Program to use this 
call.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setReportItems()

Container (packet) for items being reported. You can report the same item 
more than once in a packet if a different reason code is used each time.

  RequiredInput: No
#    Argument: 'ns:VeROReportItemsType'


=cut

=head2 getReportItems()

#    Returns: 'ns:VeROReportItemsType'


=cut

=head2 setRightsOwnerID()

User ID of the VeRO member reporting the items.

  RequiredInput: Yes
#    Argument: 'ns:UserIDType'


=cut

=head2 getRightsOwnerID()

#    Returns: 'ns:UserIDType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

