=head1 NAME

eBay::API::XML::Call::VeROReportItems::VeROReportItemsResponseType

=head1 INTERITANCE

eBay::API::XML::Call::VeROReportItems::VeROReportItemsResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Contains a packet ID and status for the items reported by the VeRO Program member.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setVeROReportPacketID()

A unique packet identifier for the items reported.

Max: Min: 
#    Argument: 'xs:long'


=cut

=head2 getVeROReportPacketID()

  Returned: Conditionally
#    Returns: 'xs:long'


=cut

=head2 setVeROReportPacketStatus()

The processing status of the packet.

#    Argument: 'ns:VeROReportPacketStatusCodeType'


=cut

=head2 getVeROReportPacketStatus()

  Returned: Conditionally
#    Returns: 'ns:VeROReportPacketStatusCodeType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

