=head1 NAME

eBay::API::XML::Call::GetClientAlertsAuthToken::GetClientAlertsAuthTokenResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetClientAlertsAuthToken::GetClientAlertsAuthTokenResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Returns a Client Alerts token.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setClientAlertsAuthToken()

This token string is required for the Login call in the Client Alerts API.
The Client Alerts GetUserAlerts call, which returns alerts about events
associated with a specific user, requires Login.

#    Argument: 'xs:string'


=cut

=head2 getClientAlertsAuthToken()

  Returned: Always
#    Returns: 'xs:string'


=cut

=head2 setHardExpirationTime()

A Client Alerts token expires after seven days.

#    Argument: 'xs:dateTime'


=cut

=head2 getHardExpirationTime()

  Returned: Always
#    Returns: 'xs:dateTime'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

