=head1 NAME

eBay::API::XML::Call::GetClientAlertsAuthToken::GetClientAlertsAuthTokenRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetClientAlertsAuthToken::GetClientAlertsAuthTokenRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Retrieves a token required for the GetUserAlerts call in the Client Alerts API.
Required input is a valid user token, which is the same user token used for
authentication and authorization in the Trading API. Client Alerts token also
required for Client Alerts API calls Login and Logout.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

