=head1 NAME

eBay::API::XML::Call::AddMemberMessagesAAQToBidder::AddMemberMessagesAAQToBidderResponseType

=head1 DESCRIPTION

Contains the response information.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setAddMemberMessagesAAQToBidderResponseContainer()

Contains the response information.

#    Argument: reference to an array  
                      of 'ns:AddMemberMessagesAAQToBidderResponseContainerType'


=cut

=head2 getAddMemberMessagesAAQToBidderResponseContainer()

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:AddMemberMessagesAAQToBidderResponseContainerType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

