=head1 NAME

eBay::API::XML::Call::SetStore::SetStoreResponseType

=head1 DESCRIPTION

Returned after calling SetStoreRequest. This serves as confirmation that
the Store configuration was successfully submitted.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

