=head1 eBay::API::XML::Call::SetStore::SetStoreResponseType

eBay::API::XML::Call::SetStore::SetStoreResponseType

=head1 DESCRIPTION

Returned after calling SetStoreRequest. This serves as confirmation that
the Store configuration was successfully submitted.



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

