=head1 NAME

eBay::API::XML::Call::SetUserPreferences::SetUserPreferencesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::SetUserPreferences::SetUserPreferencesResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Returned after a call to SetUserPreferences to indicate that the call succeeded.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

