=head1 NAME

eBay::API::XML::Call::GetAttributesXSL::GetAttributesXSLResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetAttributesXSL::GetAttributesXSLResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Retrieves the Item Specifics SYI XSL stylesheet.Apply the stylesheet to the
XML returned from a call to GetAttributesCS or GetProductSellingPages to
render a form like the Item Specifics portion of eBay's Title and Description page.
See the Developer's Guide for an overview of Item Specifics and information
on working with the XSL.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setXSLFile()

Child elements contain data related to one XSL file.
Multiple XSLFile objects can be returned. However, currently only
one is returned.

#    Argument: reference to an array  
                      of 'ns:XSLFileType'


=cut

=head2 getXSLFile()

  Returned: Always
  Details: DetailLevel: none, ReturnAll
#    Returns: reference to an array  
                      of 'ns:XSLFileType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

