=head1 NAME

eBay::API::XML::Call::SetShippingDiscountProfiles::SetShippingDiscountProfilesResponseType

=head1 DESCRIPTION

The response to a call of SetShippingDiscountProfiles.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

