=head1 NAME

eBay::API::XML::Call::SetStorePreferences::SetStorePreferencesRequestType

=head1 INTERITANCE

eBay::API::XML::Call::SetStorePreferences::SetStorePreferencesRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Sets the preferences for a user's eBay Store. These preferences include various
seller vacation options.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setStorePreferences()

Specifies the store preferences.

  RequiredInput: No
#    Argument: 'ns:StorePreferencesType'


=cut

=head2 getStorePreferences()

#    Returns: 'ns:StorePreferencesType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

