=head1 eBay::API::XML::Call::ReviseLiveAuctionItem::ReviseLiveAuctionItemRequestType

eBay::API::XML::Call::ReviseLiveAuctionItem::ReviseLiveAuctionItemRequestType

=head1 DESCRIPTION

Enables a seller to make changes to the definition of an active item
listing that listed for the Live Auction.



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setDeletedField()

Reserved for future use.

  RequiredInput: No
#    Argument: reference to an array  
                      of 'xs:string'


=cut

=head2 getDeletedField()

#    Returns: reference to an array  
                      of 'xs:string'


=cut

=head2 setItem()

Child elements hold the values for properties that are changing.
The Item.ID property must always be set to the ID of the listing
being changed. Set other fields in the Item object only for those
properties that are changing.

  RequiredInput: Yes
#    Argument: 'ns:ItemType'


=cut

=head2 getItem()

#    Returns: 'ns:ItemType'


=cut

