=head1 NAME

eBay::API::XML::Call::ReviseLiveAuctionItem::ReviseLiveAuctionItemResponseType

=head1 INTERITANCE

eBay::API::XML::Call::ReviseLiveAuctionItem::ReviseLiveAuctionItemResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Returns the item ID and the estimated fees for the revised listing.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setCategory2ID()

ID of the secondary category in which the item was listed.
Only returned if you set Item.CategoryMappingAllowed to true in the request
and the ID passed in Item.SecondaryCategory was mapped to a new ID by eBay.
If the secondary category has not changed or it has expired with no replacement,
Category2ID does not return a value.

MaxLength: 10

#    Argument: 'xs:string'


=cut

=head2 getCategory2ID()

  Returned: Conditionally
#    Returns: 'xs:string'


=cut

=head2 setCategoryID()

ID of the primary category in which the item was listed.
Only returned if you set Item.CategoryMappingAllowed to true in the request
and the ID passed in Item.PrimaryCategory was mapped to a new ID by eBay.
If the primary category has not changed or it has expired with no replacement,
CategoryID does not return a value.

MaxLength: 10

#    Argument: 'xs:string'


=cut

=head2 getCategoryID()

  Returned: Conditionally
#    Returns: 'xs:string'


=cut

=head2 setFees()

Child elements contain the estimated listing fees for the revised item
listing. The fees do not include the Final Value Fee (FVF), which cannot
be determined until an item is sold. Revising an item does not itself
incur a fee. However, certain item properties are fee-based and result
in the return of fees in the call's response.

#    Argument: 'ns:FeesType'


=cut

=head2 getFees()

  Returned: Always
#    Returns: 'ns:FeesType'


=cut

=head2 setItemID()

Item ID that uniquely identifies the item listing that was revised.
Provided for confirmation purposes. The value returned should be the
same as the item ID specified in the ItemID property of the Item object
specified as input for the call.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, Item IDs are usually 9 to 12 digits)

#    Argument: 'ns:ItemIDType'


=cut

=head2 getItemID()

  Returned: Always
#    Returns: 'ns:ItemIDType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

