=head1 NAME

eBay::API::XML::Call::SellerReverseDispute::SellerReverseDisputeResponseType

=head1 INTERITANCE

eBay::API::XML::Call::SellerReverseDispute::SellerReverseDisputeResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Returned after calling SellerReverseDisputeRequest. Contains the status
of the call and any errors or warnings.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

