=head1 NAME

eBay::API::XML::Call::GetMemberMessages::GetMemberMessagesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetMemberMessages::GetMemberMessagesResponseType inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setHasMoreItems()

Specifies whether the response has more items.

#    Argument: 'xs:boolean'


=cut

=head2 isHasMoreItems()

  Returned: Always
#    Returns: 'xs:boolean'


=cut

=head2 setMemberMessage()

The returned member messages. Returned if messages that meet the request criteria exist.

#    Argument: 'ns:MemberMessageExchangeArrayType'


=cut

=head2 getMemberMessage()

  Returned: Conditionally
#    Returns: 'ns:MemberMessageExchangeArrayType'


=cut

=head2 setPaginationResult()

Shows the pagination of data returned by requests.

#    Argument: 'ns:PaginationResultType'


=cut

=head2 getPaginationResult()

  Returned: Always
#    Returns: 'ns:PaginationResultType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

