=head1 NAME

eBay::API::XML::Call::GetNotificationPreferences::GetNotificationPreferencesRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetNotificationPreferences::GetNotificationPreferencesRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Retrieves the requesting application's notification preferences.
Details are only returned for events for which a preference was
set at one point. For example, if you enabled notification for
the EndOfAuction event and later disabled it, the GetNotificationPreferences
response would cite the EndOfAuction event preference as
Disabled. Otherwise, no details would be returned regarding EndOfAuction.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setPreferenceLevel()

Specifies what type of Preference to retrieve.

  RequiredInput: Yes
#    Argument: 'ns:NotificationRoleCodeType'


=cut

=head2 getPreferenceLevel()

#    Returns: 'ns:NotificationRoleCodeType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

