=head1 NAME

eBay::API::XML::Call::RevokeToken::RevokeTokenRequestType

=head1 INTERITANCE

eBay::API::XML::Call::RevokeToken::RevokeTokenRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Revokes a user token. The full set of developer keys is required for the RevokeToken
call.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setUnsubscribeNotification()

Cancels notification subscriptions for the user/application if set to true. Default value is false.

  RequiredInput: No
#    Argument: 'xs:boolean'


=cut

=head2 isUnsubscribeNotification()

#    Returns: 'xs:boolean'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

