=head1 NAME

eBay::API::XML::Call::GetStoreCustomPage::GetStoreCustomPageResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetStoreCustomPage::GetStoreCustomPageResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Contains the custom page or pages for the user's Store.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setCustomPageArray()

The custom page or custom pages.

#    Argument: 'ns:StoreCustomPageArrayType'


=cut

=head2 getCustomPageArray()

  Returned: Always
#    Returns: 'ns:StoreCustomPageArrayType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

