=head1 NAME

eBay::API::XML::Call::GetStoreCustomPage::GetStoreCustomPageRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetStoreCustomPage::GetStoreCustomPageRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Retrieves the custom page or pages for the user's Store.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setPageID()

If a PageID is specified, then that page is returned, and
the returned page contains the page Content.
If no PageID is specified, then all pages are returned, without
the page Content.

  RequiredInput: No
#    Argument: 'xs:long'


=cut

=head2 getPageID()

#    Returns: 'xs:long'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

