=head1 NAME

eBay::API::XML::Call::GetTaxTable::GetTaxTableRequestType

=head1 DESCRIPTION

Retrieves the tax table for a user on a given site or retrieves the valid
jurisdictions (if any) for a given site.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

