=head1 NAME

eBay::API::XML::Call::GetStoreCategoryUpdateStatus::GetStoreCategoryUpdateStatusRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetStoreCategoryUpdateStatus::GetStoreCategoryUpdateStatusRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Returns the status of the processing progress for category structure changes
specified with a SetStoreCategories request. Use this call to retrieve status
when the SetStoreCategories call is being processed asynchronously.
SetStoreCategories will be processed asynchronously when many listings are
affected by the category structure changes.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setTaskID()

The task ID returned by the SetStoreCategories call. If the
SetStoreCategories call was processed asynchronously, the TaskID will be
a positive number, otherwise the TaskID will be 0.

  RequiredInput: Yes
#    Argument: 'xs:long'


=cut

=head2 getTaskID()

#    Returns: 'xs:long'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

