=head1 NAME

eBay::API::XML::Call::GetPictureManagerOptions::GetPictureManagerOptionsRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetPictureManagerOptions::GetPictureManagerOptionsRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Requests a list of Picture Manager options and allowed values,
such as subscription type and picture display.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

