=head1 NAME

eBay::API::XML::Call::GetMyeBayReminders::GetMyeBayRemindersRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetMyeBayReminders::GetMyeBayRemindersRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Requests reminder type totals from the user's MyeBay account.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setBuyingReminders()

Specifies the type of buying reminders for which you want information.

  RequiredInput: No
#    Argument: 'ns:ReminderCustomizationType'


=cut

=head2 getBuyingReminders()

#    Returns: 'ns:ReminderCustomizationType'


=cut

=head2 setSellingReminders()

Specifies the type of selling reminders for which you want information.

  RequiredInput: No
#    Argument: 'ns:ReminderCustomizationType'


=cut

=head2 getSellingReminders()

#    Returns: 'ns:ReminderCustomizationType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

