=head1 NAME

eBay::API::XML::Call::IssueRefund::IssueRefundResponseType

=head1 INTERITANCE

eBay::API::XML::Call::IssueRefund::IssueRefundResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Indicates the refund amount that a seller issued to a buyer for a single Half.com transaction.
Refunds may only be issued for a specific transaction. Sellers do not have the ability to issue a 
general refund (not tied to a transaction) to a buyer.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setRefundFromSeller()

Total amount that the seller asked Half.com to refund to 
a buyer for a Half.com transaction.

#    Argument: 'ns:AmountType'


=cut

=head2 getRefundFromSeller()

  Returned: Always
#    Returns: 'ns:AmountType'


=cut

=head2 setTotalRefundToBuyer()

Total amount that Half.com refunded to the buyer (which could include the refund amount 
from the seller plus a refund amount from Half.com).

#    Argument: 'ns:AmountType'


=cut

=head2 getTotalRefundToBuyer()

  Returned: Always
#    Returns: 'ns:AmountType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

