=head1 NAME

eBay::API::XML::Call::AddToWatchList

=head1 INTERITANCE

eBay::API::XML::Call::AddToWatchList inherits from the L<eBay::API::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setItemID()

The ItemID of the item that is to be added to the watch list. The item
must be a currently active item, and the total number of items in the
watchlist (after the items in the request have been added) cannot exceed
the maximum allowed number of watch list items. One or more ItemIDs can be
specified, each in its own ItemID container. A separate error node will be
returned for each item that fails.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, Item IDs are usually 9 to 12 digits)

  RequiredInput: Yes
#    Argument: reference to an array  
                      of 'ns:ItemIDType'


=cut

=head2 getWatchListCount()

The number of items in the user's watch list (after those specified
in the call request have been added)

  Returned: Always
#    Returns: 'xs:int'


=cut

=head2 getWatchListMaximum()

The maximum number of items allowed in watch lists. Currently this
value is the same for all sites and all users.

  Returned: Always
#    Returns: 'xs:int'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

