=head1 NAME

eBay::API::XML::Call::GeteBayDetails

=head1 INTERITANCE

eBay::API::XML::Call::GeteBayDetails inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setDetailName()

A designation of what kind of information you wish returned
for the specified eBay site. If omitted, all details are
returned.
The possible values for input (the enumeration values of
DetailNameCodeType) are the same name as fields returned by
the response. See the documentation for the
GeteBayDetails response to better understand the DetailName
options.

  RequiredInput: No
#    Argument: reference to an array  
                      of 'ns:DetailNameCodeType'


=cut

=head2 getCountryDetails()

Details about a specific country. GeteBayDetails returns all countries in
the system, regardless of the site to which you sent the request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:CountryDetailsType'


=cut

=head2 getCurrencyDetails()

Details about a specific currency that can be used for listing on an eBay
site. GeteBayDetails returns all site currencies in the system, regardless
of the site to which you sent the request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:CurrencyDetailsType'


=cut

=head2 getDispatchTimeMaxDetails()

Details about a specific max dispatch time. A dispatch time specifies the
maximum number of business days a seller commits to for shipping an item
to domestic buyers after receiving a cleared payment. GeteBayDetails
returns all dispatch times in the system, regardless of the site to which
you sent the request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:DispatchTimeMaxDetailsType'


=cut

=head2 getItemSpecificDetails()

The site's validation rules (e.g., string lengths) for custom Item Specifics.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:ItemSpecificDetailsType'


=cut

=head2 getPaymentOptionDetails()

Details about a specific buyer payment method. GeteBayDetails only returns
payment methods that are applicable to the site to which you sent the
request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:PaymentOptionDetailsType'


=cut

=head2 getRegionDetails()

[Ignorable region values for all sites.]

  Returned: Conditionally
  Ignore: 
#    Returns: reference to an array  
                      of 'ns:RegionDetailsType'


=cut

=head2 getRegionOfOriginDetails()

Details about the region of origin, specific to a site.

  Returned: Conditionally
  Ignore: 
#    Returns: reference to an array  
                      of 'ns:RegionOfOriginDetailsType'


=cut

=head2 getShippingCarrierDetails()

The kinds of carrier supported by this shipping service.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:ShippingCarrierDetailsType'


=cut

=head2 getShippingLocationDetails()

Details about a location or region to which the seller is willing to ship.
GeteBayDetails returns all shipping locations in the system, regardless of
the site to which you sent the request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:ShippingLocationDetailsType'


=cut

=head2 getShippingPackageDetails()

Details about various shipping packages.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:ShippingPackageDetailsType'


=cut

=head2 getShippingServiceDetails()

Details about a specific shipping service. GeteBayDetails only returns
shipping services that are applicable to the site to which you sent the
request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:ShippingServiceDetailsType'


=cut

=head2 getSiteDetails()

Details about a specific eBay site. GeteBayDetails returns all sites in
the system, regardless of the site to which you sent the request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:SiteDetailsType'


=cut

=head2 getTaxJurisdiction()

Details about a specific tax jurisdiction or tax region. GeteBayDetails
only returns jurisdictions that are applicable to the site to which you
sent the request.<br><br>
Related fields:<br>
TaxTable.TaxJurisdiction in SetTaxTable<br>
Item.UseTaxTable in Additem

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:TaxJurisdictionType'


=cut

=head2 getTimeZoneDetails()

Details about a specific eBay time zone. GeteBayDetails returns all time
zones eBay supports.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:TimeZoneDetailsType'


=cut

=head2 getURLDetails()

Details about a specific eBay URL. GeteBayDetails only returns URLs that
are applicable to the site to which you sent the request.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:URLDetailsType'


=cut

=head2 getUnitOfMeasurementDetails()

Suggested text to use when specifying units of measure in custom Item Specifics.

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:UnitOfMeasurementDetailsType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

