=head1 NAME

eBay::API::XML::Call::GetItemsAwaitingFeedback

=head1 INTERITANCE

eBay::API::XML::Call::GetItemsAwaitingFeedback inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setPagination()

Specifies the number of entries per page and the page number to return
in the result set.

  RequiredInput: No
#    Argument: 'ns:PaginationType'


=cut

=head2 setSort()

Specifies how the returned feedback items should be sorted. 
Valid values are Title, EndTime, QuestionCount, FeedbackLeft, FeedbackReceivedDescending, UserIDDescending, TitleDescending, 
and EndTimeDescending.

  RequiredInput: No
#    Argument: 'ns:ItemSortTypeCodeType'


=cut

=head2 getItemsAwaitingFeedback()

Contains the items awaiting feedback.
Returned only if there are items that do not yet
have feedback.

  Returned: Always
#    Returns: 'ns:PaginatedTransactionArrayType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

