=head1 NAME

eBay::API::XML::Call::GetMyeBaySelling

=head1 INTERITANCE

eBay::API::XML::Call::GetMyeBaySelling inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setActiveList()

Contains the list of items the user is actively selling whose listings are active.
Valid subelements are Sort, IncludeNotes, Pagination, and ListingType (with valid
values Auction, FixedPriceItem, StoresFixedPrice, or AdType).
Note that if a DetailLevel of ReturnAll is specified in the request, this element is ignored as a way to filter the response, and ALL containers are returned.

  RequiredInput: No
#    Argument: 'ns:ItemListCustomizationType'


=cut

=head2 setScheduledList()

Contains the list of items the user has scheduled to sell but whose listings have not yet opened.
Valid subelements are Sort, IncludeNotes, and Pagination.

  RequiredInput: No
#    Argument: 'ns:ItemListCustomizationType'


=cut

=head2 setSoldList()

Contains the list of items the user has sold. Valid subelements are DurationInDays
(with valid values 0-60), IncludeNotes, and Pagination.
Note that if a DetailLevel of ReturnAll is specified in the request, this element is ignored as a way to filter the response, and ALL containers are returned.

  RequiredInput: No
#    Argument: 'ns:ItemListCustomizationType'


=cut

=head2 setUnsoldList()

Contains the list of items the user has listed but whose listings have ended
without being sold. Valid subelements are DurationInDays (with valid values 0-60),
Sort, IncludeNotes, and Pagination.
Note that if a DetailLevel of ReturnAll is specified in the request, this element is ignored as a way to filter the response, and ALL containers are returned.

  RequiredInput: No
#    Argument: 'ns:ItemListCustomizationType'


=cut

=head2 getActiveList()

Contains the items the user is selling that have active listings.

  Returned: Conditionally
  Details: DetailLevel: none, ReturnSummary, ReturnAll
#    Returns: 'ns:PaginatedItemArrayType'


=cut

=head2 getScheduledList()

Contains the items the user has scheduled for sale, but whose listings have
not yet started.

  Returned: Conditionally
  Details: DetailLevel: none, ReturnSummary, ReturnAll
#    Returns: 'ns:PaginatedItemArrayType'


=cut

=head2 getSellingSummary()

Contains summary information about the items the user is selling.

  Returned: Always
  Details: DetailLevel: none, ReturnSummary, ReturnAll
#    Returns: 'ns:SellingSummaryType'


=cut

=head2 getSoldList()

Contains the items the user has sold.

  Returned: Conditionally
  Details: DetailLevel: none, ReturnSummary, ReturnAll
#    Returns: 'ns:PaginatedOrderTransactionArrayType'


=cut

=head2 getSummary()

Contains summary information about the items the user is selling.

  Returned: Always
  Details: DetailLevel: none, ReturnSummary, ReturnAll
#    Returns: 'ns:MyeBaySellingSummaryType'


=cut

=head2 getUnsoldList()

Contains the items whose listings have ended but that have not sold.

  Returned: Conditionally
  Details: DetailLevel: none, ReturnSummary, ReturnAll
#    Returns: 'ns:PaginatedItemArrayType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

