=head1 NAME

eBay::API::XML::Call::GetPromotionRules

=head1 INTERITANCE

eBay::API::XML::Call::GetPromotionRules inherits from the L<eBay::API::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setItemID()

The unique ID of the item for which to retrieve promotion rules.
Mutually exclusive with StoreCategoryID.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, Item IDs are usually 9 to 12 digits)

  RequiredInput: Conditionally
#    Argument: 'ns:ItemIDType'


=cut

=head2 setPromotionMethod()

The type of promotion. (CrossSell: items that are related to or
useful in combination with this item. UpSell: items that are more
expensive than or of higher quality than this item.)

  RequiredInput: Yes
#    Argument: 'ns:PromotionMethodCodeType'


=cut

=head2 setStoreCategoryID()

The unique ID of the store category for which to retrieve promotion rules.
Mutually exclusive with ItemID.

  RequiredInput: Conditionally
#    Argument: 'xs:long'


=cut

=head2 getPromotionRuleArray()

An array of promotion rules associated with the item or store category
specified in the request.

  Returned: Always
#    Returns: 'ns:PromotionRuleArrayType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

