=head1 NAME

eBay::API::XML::Call::GetProductFamilyMembers

=head1 INTERITANCE

eBay::API::XML::Call::GetProductFamilyMembers inherits from the L<eBay::API::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setProductSearch()

Specifies the ID of a product in the family to be retrieved,
along with pagination and sorting instructions.
ProductSearch is a required input.

SeeLink: URL: http://developer.ebay.com/DevZone/XML/docs/WebHelp/index.htm?context=eBay_XML_API&topic=AttrGPFM
Title: Retrieving All Members of a Product Family

  RequiredInput: Yes
#    Argument: reference to an array  
                      of 'ns:ProductSearchType'


=cut

=head2 getDataElementSets()

Container for one or more DataElement fields containing supplemental helpful data.
A DataElement field is an HTML snippet that specifies hints for the user, help links,
help graphics, and other supplemental information that varies per characteristics set.
Usage of this information is optional and may require developers to inspect the information
to determine how it can be applied in an application.

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:DataElementSetType'


=cut

=head2 getProductSearchResult()

Contains the attributes and summary product details for all products that match
the product ID (or IDs) passed in the request.

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:ProductSearchResultType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

