=head1 NAME

eBay::API::XML::Call::GetPictureManagerOptions

=head1 INTERITANCE

eBay::API::XML::Call::GetPictureManagerOptions inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 getPictureType()

A global definition for displaying pictures, with a maximum size.

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:PictureManagerPictureDisplayType'


=cut

=head2 getSubscription()

A type of Picture Manager subscription, with a subscription level, fee,
and allowed storage size.

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:PictureManagerSubscriptionType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

