=head1 NAME

eBay::API::XML::Call::GetRuName

=head1 INTERITANCE

eBay::API::XML::Call::GetRuName inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setClientUseCase()

Optional value that is appended to the generated runame.

  RequiredInput: No
#    Argument: 'xs:string'


=cut

=head2 getRuName()

The generated globally unique runame.

  Returned: Always
#    Returns: 'xs:string'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

