=head1 NAME

eBay::API::XML::Call::GetStorePreferences

=head1 INTERITANCE

eBay::API::XML::Call::GetStorePreferences inherits from the L<eBay::API::BaseCall> class

=cut

=head1 Methods


=cut

=head2 getStorePreferences()

The user's Store preferences.

  Returned: Always
#    Returns: 'ns:StorePreferencesType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

