=head1 NAME

eBay::API::XML::Call::GetStoreOptions

=head1 INTERITANCE

eBay::API::XML::Call::GetStoreOptions inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 getAdvancedThemeArray()

The current set of advances themes. Unlike basic themes, you
can use any color	scheme with an advanced theme. These themes 
are suitable for more advanced customization.

  Returned: Always
#    Returns: 'ns:StoreThemeArrayType'


=cut

=head2 getBasicThemeArray()

The current set of basic themes. Each basic theme definition
specifies a valid color scheme for the theme.

  Returned: Always
#    Returns: 'ns:StoreThemeArrayType'


=cut

=head2 getLogoArray()

The current set of Store logos. These logos are used in the Store header.

  Returned: Always
#    Returns: 'ns:StoreLogoArrayType'


=cut

=head2 getMaxCategories()

The maximum number of categories in this store.

  Returned: Always
#    Returns: 'xs:int'


=cut

=head2 getMaxCategoryLevels()

The maximum number of category levels in this store.

  Returned: Always
#    Returns: 'xs:int'


=cut

=head2 getSubscriptionArray()

The current set of eBay Store subscription tiers and corresponding 
subscription prices.

  Returned: Always
#    Returns: 'ns:StoreSubscriptionArrayType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

