=head1 NAME

eBay::API::XML::Call::GetTaxTable

=head1 INTERITANCE

eBay::API::XML::Call::GetTaxTable inherits from the L<eBay::API::BaseCall> class

=cut

=head1 Methods


=cut

=head2 getLastUpdateTime()

The last time (in GMT) that the tax table was updated.
Only returned if the user previously created a tax table
and if the site has jurisdictions.
LastUpdateTime is useful for synchronization. If you cache the user's
tax table, you can use GetTaxTable to check if it has changed and
whether you need to update the cached tax table.

  Returned: Conditionally
  Details: DetailLevel: ReturnAll, none
#    Returns: 'xs:dateTime'


=cut

=head2 getTaxTable()

A container of tax jurisdiction information unique to
a user/site combination. Empty if not set for user.
If DetailLevel is not specified, information is only
returned for the jurisdictions for which the user provided tax
information. If DetailLevel is ReturnAll, tax information
is returned for all possible jurisdictions, whether
specified by the user or not. ShippingIncludedInTax and
SalesTaxPercent are returned but are empty.

  Returned: Always
  Details: DetailLevel: ReturnAll, none
#    Returns: 'ns:TaxTableType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

