=head1 NAME

eBay::API::XML::Call::GetVeROReasonCodeDetails

=head1 INTERITANCE

eBay::API::XML::Call::GetVeROReasonCodeDetails inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setReasonCodeID()

Unique identifier for a reason code. If this ReasonCodeID is passed then 
only details of this ReasonCodeID will be returned. If no reason code is 
specified, all reason codes are returned.

Max: Default: Min: 
  RequiredInput: Conditionally
#    Argument: 'xs:long'


=cut

=head2 setReturnAllSites()

Set to true to retrieve reason codes for all sites. If not specified, 
reason codes are returned for the site specified in the request header 
only. 
If ReasonCodeID is specified, this parameter is ignored.

Default: false

  RequiredInput: No
#    Argument: 'xs:boolean'


=cut

=head2 getVeROReasonCodeDetails()

Contains the list of the status codes for a site.

  Returned: Always
#    Returns: 'ns:VeROReasonCodeDetailsType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

