=head1 eBay::API::XML::Call::RespondToFeedback

eBay::API::XML::Call::RespondToFeedback

=head1 DESCRIPTION



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setFeedbackID()

ID that uniquely identifies the feedback.
FeedbackIDs can be retrieved by using
GetFeedback. Required if ItemID is not
specified.

  RequiredInput: Conditionally
#    Argument: 'xs:string'


=cut

=head2 setItemID()

Unique identifier of an item to which the
feedback is attached. Required if FeedbackID is
not provided.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, Item IDs are usually 9 to 12 digits)

  RequiredInput: Conditionally
#    Argument: 'ns:ItemIDType'


=cut

=head2 setResponseText()

Textual comment that the user who is
subject of feedback may leave in response or
rebuttal to the feedback. Alternatively, when
the  ResponseType is FollowUp, this value
contains the text of the follow-up comment. Max
length is 125 for the Taiwan site.

MaxLength: 80

  RequiredInput: Yes
#    Argument: 'xs:string'


=cut

=head2 setResponseType()

Specifies whether the response is a reply
or a follow-up.

  RequiredInput: Yes
#    Argument: 'ns:FeedbackResponseCodeType'


=cut

=head2 setTargetUserID()

User who left the feedback that is being
replied to or followed up on.

  RequiredInput: Yes
#    Argument: 'ns:UserIDType'


=cut

=head2 setTransactionID()

Unique identifier for a purchase from an
eBay Stores Inventory or basic fixed price
listing. If TransactionID is specified, ItemID
must also be specified.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, transaction IDs are usually 9 to 12 digits.)

  RequiredInput: No
#    Argument: 'xs:string'


=cut

