=head1 NAME

eBay::API::XML::Call::ReviseCheckoutStatus

=head1 DESCRIPTION



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setAdjustmentAmount()

Discount or charge agreed to by the buyer and seller. A positive value
indicates that the amount is an extra charge being paid to the seller by
the buyer. A negative value indicates that the amount is a discount given
to the buyer by the seller.

  RequiredInput: No
#    Argument: 'ns:AmountType'


=cut

=head2 setAmountPaid()

The amount paid by the buyer. For an eBay Stores item, the value passed in
AmountPaid is the transaction/item price. For a US eBay Motors item,
AmountPaid is the total amount paid by the buyer for the deposit.

  RequiredInput: No
#    Argument: 'ns:AmountType'


=cut

=head2 setBuyerID()

eBay ID for the buyer in the transaction being revised. A transaction is
uniquely identified by one of two means: (a) You provide a TransactionID
and ItemID. (This is the preferred approach.), OR, (b) You provide a
BuyerID and ItemID and eBay identifies only one transaction for that
combination (an error is returned if there are multiple transactions for
that combination). Note: If all three are provided (that is, BuyerID,
ItemID and TransactionID), BuyerID is ignored.

  RequiredInput: Conditionally
#    Argument: 'xs:string'


=cut

=head2 setCODCost()

Italy site (site ID 101) only.
Enables you to specify the cash-on-delivery (COD) cost, for COD shipping.

SeeLink: URL: http://developer.ebay.com/DevZone/XML/docs/WebHelp/index.htm?context=eBay_XML_API&topic=CODInShippingDetails
Title: Specifying the Cash on Delivery Option in Shipping Details

  RequiredInput: No
#    Argument: 'ns:AmountType'


=cut

=head2 setCheckoutMethod()

Not supported.

  RequiredInput: No
#    Argument: 'ns:CheckoutMethodCodeType'


=cut

=head2 setCheckoutStatus()

The current status of the checkout process for the transaction.

  RequiredInput: Yes
#    Argument: 'ns:CompleteStatusCodeType'


=cut

=head2 setEncryptedID()

Not supported.

MaxLength: 20

  RequiredInput: No
#    Argument: 'xs:string'


=cut

=head2 setExternalTransaction()

Not supported.

  RequiredInput: No
#    Argument: 'ns:ExternalTransactionType'


=cut

=head2 setInsuranceType()

The insurance option selected by the buyer.

  RequiredInput: No
#    Argument: 'ns:InsuranceSelectedCodeType'


=cut

=head2 setItemID()

Unique ID for the item associated with the checkout. A transaction is
uniquely identified by one of two means: (a) You provide a TransactionID
and ItemID. (This is the preferred approach.), OR, (b) You provide a
BuyerID and ItemID and eBay identifies only one transaction for that
combination (an error is returned if there are multiple transactions for
that combination). Note: If all three are provided (that is, BuyerID,
ItemID and TransactionID), BuyerID is ignored.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, Item IDs are usually 9 to 12 digits)

  RequiredInput: Yes
#    Argument: 'ns:ItemIDType'


=cut

=head2 setMultipleSellerPaymentID()

Not supported.

  RequiredInput: No
#    Argument: 'xs:string'


=cut

=head2 setOrderID()

Unique ID for a multi-item order. If specified, ItemID and
TransactionID are ignored if specified in the same call.
Changes to the checkout status are applied to the specified
order as a whole (and thus the child transactions
associated with the order).

  RequiredInput: No
#    Argument: 'xs:string'


=cut

=head2 setPaymentMethodUsed()

Payment method used by the buyer.
Required if CheckoutStatus is Complete.
(Please note that only PayPal can set this value to PayPal.)

AllValuesExcept: PayPal

  RequiredInput: Conditionally
#    Argument: 'ns:BuyerPaymentMethodCodeType'


=cut

=head2 setPaymentStatus()

Not supported.

  RequiredInput: No
#    Argument: 'ns:RCSPaymentStatusCodeType'


=cut

=head2 setSalesTax()

Amount of money paid for sales tax. For Third-Party Checkout
applications.

  RequiredInput: No
#    Argument: 'ns:AmountType'


=cut

=head2 setShippingAddress()

For internal use.

  RequiredInput: No
#    Argument: 'ns:AddressType'


=cut

=head2 setShippingCost()

Amount of money paid for shipping. For Third-party Checkout
applications.

  RequiredInput: No
#    Argument: 'ns:AmountType'


=cut

=head2 setShippingIncludedInTax()

An indicator of whether shipping costs were included in the
taxable amount. For Third-Party Checkout applications.

Default: false

  RequiredInput: No
#    Argument: 'xs:boolean'


=cut

=head2 setShippingInsuranceCost()

Amount of money paid for insurance. For Third Party Checkout
applications.

  RequiredInput: No
#    Argument: 'ns:AmountType'


=cut

=head2 setShippingService()

The shipping service selected by the buyer from among the shipping
services offered by the seller (such as UPS Ground). For a list of valid
values that you can cache for future use, call GeteBayDetails with
DetailName set to ShippingServiceDetails.

  RequiredInput: No
#    Argument: 'xs:token'


=cut

=head2 setTransactionID()

Unique ID for the transaction associated with the checkout. For Chinese
auctions, the value passed in the TransactionID argument must be 0 or the
call will fail with an error. For all other auction types, TransactionID
accepts the actual, nonzero transaction ID. Call GetItemTransactionsCall
or GetSellerTransactionsCall to determine the correct transaction ID. A
transaction is uniquely identified by one of two means: (a) You provide a
TransactionID and ItemID. (This is the preferred approach.), OR, (b) You
provide a BuyerID and ItemID and eBay identifies only one transaction for
that combination (an error is returned if there are multiple transactions
for that combination). Note: If all three are provided (that is, BuyerID,
ItemID and TransactionID), BuyerID is ignored.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, transaction IDs are usually 9 to 12 digits.)

  RequiredInput: Conditionally
#    Argument: 'xs:string'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

