=head1 eBay::API::XML::Call::SellerReverseDispute

eBay::API::XML::Call::SellerReverseDispute

=head1 DESCRIPTION



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setDisputeID()

The unique identifier of the dispute that was returned when the dispute was created.
The dispute must be an Unpaid Item dispute that the seller opened.

  RequiredInput: Yes
#    Argument: 'ns:DisputeIDType'


=cut

=head2 setDisputeResolutionReason()

The reason the dispute is being reversed.

  RequiredInput: Yes
#    Argument: 'ns:DisputeResolutionReasonCodeType'


=cut

