=head1 NAME

eBay::API::XML::Call::SetPromotionalSale

=head1 INTERITANCE

eBay::API::XML::Call::SetPromotionalSale inherits from the L<eBay::API::XML::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setAction()

Specifies adding, removing, or modifying promotional sales.

  RequiredInput: Yes
#    Argument: 'ns:ModifyActionCodeType'


=cut

=head2 setPromotionalSaleDetails()

Specifies details about the promotional sale.

  RequiredInput: Yes
#    Argument: 'ns:PromotionalSaleType'


=cut

=head2 getPromotionalSaleID()

Contains the ID of a promotional sale.

  Returned: Always
#    Returns: 'xs:long'


=cut

=head2 getStatus()

Contains the status of a promotional sale.

  Returned: Always
#    Returns: 'ns:PromotionalSaleStatusCodeType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

