=head1 NAME

eBay::API::XML::Call::SetReturnURL

=head1 INTERITANCE

eBay::API::XML::Call::SetReturnURL inherits from the L<eBay::API::BaseCall> class

=cut

=head1 Methods


=cut

=head2 setAction()

Specifies whether the authentication entry is being added, deleted, or
modified.

SeeLink: URL: http://developer.ebay.com/DevZone/XML/docs/WebHelp/index.htm?context=eBay_XML_API&topic=AuthNAuth
Title: Authentication & Authorization

  RequiredInput: Yes
#    Argument: 'ns:ModifyActionCodeType'


=cut

=head2 setApplicationDisplayName()

Sets an application display name for the eBay sign-in page.
Need not be set with every call. Optional.

SeeLink: URL: http://developer.ebay.com/DevZone/XML/docs/WebHelp/index.htm?context=eBay_XML_API&topic=AuthNAuth
Title: Authentication & Authorization

  RequiredInput: No
#    Argument: 'xs:string'


=cut

=head2 setAuthenticationEntry()

The authentication preferences and other data that you are
adding, deleting, or modifying.

SeeLink: URL: http://developer.ebay.com/DevZone/XML/docs/WebHelp/index.htm?context=eBay_XML_API&topic=AuthNAuth
Title: Authentication & Authorization

  RequiredInput: Yes
#    Argument: 'ns:AuthenticationEntryType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

