=head1 NAME

eBay::API::XML::Call::GetBidderList::GetBidderListResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetBidderList::GetBidderListResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Response to a GetBidderList call, which retrieves all items the user is currently bidding on, or
has won or purchased.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setBidItemArray()

Array of items the bidder has bid on, has won or has lost.

#    Argument: 'ns:ItemArrayType'


=cut

=head2 getBidItemArray()

  Returned: Always
#    Returns: 'ns:ItemArrayType'


=cut

=head2 setBidder()

Data for one eBay bidder.

#    Argument: 'ns:UserType'


=cut

=head2 getBidder()

  Returned: Always
#    Returns: 'ns:UserType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

