=head1 NAME

eBay::API::XML::Call::GetContextualKeywords::GetContextualKeywordsResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetContextualKeywords::GetContextualKeywordsResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Response to a GetContextualKeywords request.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setContextSearchAsset()

An array of either keyword/category pairs or categories, with ranking and score.

#    Argument: reference to an array  
                      of 'ns:ContextSearchAssetType'


=cut

=head2 getContextSearchAsset()

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:ContextSearchAssetType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

