=head1 NAME

eBay::API::XML::Call::SetNotificationPreferences::SetNotificationPreferencesResponseType

=head1 DESCRIPTION

(out) Returned after a call to SetNotificationPreferences to indicate that the call succeeded.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

