=head1 NAME

eBay::API::XML::Call::GetItem::GetItemResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetItem::GetItemResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Contains the item data returned by the call. The data for the specified item
listing is returned in an ItemType object.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setItem()

ItemType object that contains the data for the specified item.

#    Argument: 'ns:ItemType'


=cut

=head2 getItem()

  Returned: Always
  Details: DetailLevel: none, ItemReturnDescription, ItemReturnAttributes, ReturnAll
#    Returns: 'ns:ItemType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

