=head1 NAME

eBay::API::XML::Call::GetShippingDiscountProfiles::GetShippingDiscountProfilesRequestType

=head1 DESCRIPTION

Returns details of the shipping discount profiles defined by the user, along with other
combined payment-related details such as packaging/handling cost and shipping insurance.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

