=head1 NAME

eBay::API::XML::Call::AddDispute::AddDisputeResponseType

=head1 DESCRIPTION

Returned after calling AddDisputeRequest. The response confirms that
the Unpaid Item dispute was successfully created.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setDisputeID()

The unique identifier of the Unpaid Item dispute.

#    Argument: 'ns:DisputeIDType'


=cut

=head2 getDisputeID()

  Returned: Always
#    Returns: 'ns:DisputeIDType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

