=head1 NAME

eBay::API::XML::Call::ValidateChallengeInput::ValidateChallengeInputResponseType

=head1 INTERITANCE

eBay::API::XML::Call::ValidateChallengeInput::ValidateChallengeInputResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Validate the user response to botblock challenge.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setValidToken()

Indicates whether the token is valid.

#    Argument: 'xs:boolean'


=cut

=head2 isValidToken()

  Returned: Always
#    Returns: 'xs:boolean'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

