=head1 NAME

eBay::API::XML::Call::GetVeROReasonCodeDetails::GetVeROReasonCodeDetailsResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetVeROReasonCodeDetails::GetVeROReasonCodeDetailsResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Contains the reason codes for all sites.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setVeROReasonCodeDetails()

Contains the list of the status codes for a site.

#    Argument: 'ns:VeROReasonCodeDetailsType'


=cut

=head2 getVeROReasonCodeDetails()

  Returned: Always
#    Returns: 'ns:VeROReasonCodeDetailsType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

