=head1 NAME

eBay::API::XML::Call::GetCharities::GetCharitiesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetCharities::GetCharitiesResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Contains information about charity nonprofit organizations that meet the
criteria specified in the request.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setCharity()

Contains information about charity nonprofit organizations that
meet the criteria specified in the request. One Charity node is
returned for each applicable nonprofit charity organization. The
CharityID value is returned as an id attribute of this node. If no
nonprofit charity organization is applicable, this node is not
returned.

#    Argument: reference to an array  
                      of 'ns:CharityInfoType'


=cut

=head2 getCharity()

  Returned: Conditionally
#    Returns: reference to an array  
                      of 'ns:CharityInfoType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

