=head1 NAME

eBay::API::XML::Call::RespondToWantItNowPost::RespondToWantItNowPostRequestType

=head1 INTERITANCE

eBay::API::XML::Call::RespondToWantItNowPost::RespondToWantItNowPostRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Enables a seller to respond to a Want It Now post with an item listed on the eBay
site. Responses appear on the Want It Now post page, with the item title, the
price of the item, the number of bids on the item, and the time left before the
listing ends. If the item has a picture, the picture is also included on the Want
It Now post page.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setItemID()

The unique identifier of an item listed on the eBay site.

MaxLength: 19 (Note: The eBay database specifies 38. Currently, Item IDs are usually 9 to 12 digits)

  RequiredInput: Yes
#    Argument: 'ns:ItemIDType'


=cut

=head2 getItemID()

#    Returns: 'ns:ItemIDType'


=cut

=head2 setPostID()

The unique identifier of a Want It Now post on the eBay site.

  RequiredInput: Yes
#    Argument: 'ns:ItemIDType'


=cut

=head2 getPostID()

#    Returns: 'ns:ItemIDType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

