=head1 NAME

eBay::API::XML::Call::GetUserContactDetails::GetUserContactDetailsResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetUserContactDetails::GetUserContactDetailsResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Returns contact information to a seller for both bidders
and users who have made offers (via Best Offer) during
an active listing.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setContactAddress()

Contact information for the requested contact.
Note that the email address is NOT returned.

#    Argument: 'ns:AddressType'


=cut

=head2 getContactAddress()

  Returned: Always
#    Returns: 'ns:AddressType'


=cut

=head2 setRegistrationDate()

The date and time that the requested contact
registered with eBay.

#    Argument: 'xs:dateTime'


=cut

=head2 getRegistrationDate()

  Returned: Always
#    Returns: 'xs:dateTime'


=cut

=head2 setUserID()

An eBay ID that uniquely identifies a given
user. The eBay username of the requested
contact.

#    Argument: 'xs:string'


=cut

=head2 getUserID()

  Returned: Always
#    Returns: 'xs:string'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

