=head1 NAME

eBay::API::XML::Call::SetMessagePreferences::SetMessagePreferencesRequestType

=head1 INTERITANCE

eBay::API::XML::Call::SetMessagePreferences::SetMessagePreferencesRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Enables a seller to add custom Ask Seller a Question (ASQ)
subjects to display on the seller's Ask a Question page, or
reset custom subjects to their default values.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setASQPreferences()

Contains custom ASQ subjects or a flag to reset those
subjects to their default values.

  RequiredInput: No
#    Argument: 'ns:ASQPreferencesType'


=cut

=head2 getASQPreferences()

#    Returns: 'ns:ASQPreferencesType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

