=head1 NAME

eBay::API::XML::Call::SetMessagePreferences::SetMessagePreferencesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::SetMessagePreferences::SetMessagePreferencesResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Returns the success or failure of the
SetMessagePreferencesRequest, and any applicable errors.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

