=head1 NAME

eBay::API::XML::Call::SetPromotionalSale::SetPromotionalSaleResponseType

=head1 INTERITANCE

eBay::API::XML::Call::SetPromotionalSale::SetPromotionalSaleResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Contains the ID and status of a promotional sale.
The Promotional Price Display feature enables sellers
to apply discounts and/or free shipping across many listings.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setPromotionalSaleID()

Contains the ID of a promotional sale.

#    Argument: 'xs:long'


=cut

=head2 getPromotionalSaleID()

  Returned: Always
#    Returns: 'xs:long'


=cut

=head2 setStatus()

Contains the status of a promotional sale.

#    Argument: 'ns:PromotionalSaleStatusCodeType'


=cut

=head2 getStatus()

  Returned: Always
#    Returns: 'ns:PromotionalSaleStatusCodeType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

