=head1 NAME

eBay::API::XML::Call::GetLiveAuctionCatalogDetails::GetLiveAuctionCatalogDetailsRequestType

=head1 DESCRIPTION

Retrieves all the eBay Live Auctions catalogs and upcoming sale
schedules that the user has created. Only returns data if the
requestor is an authorized eBay Live Auctions seller with at least
one catalog. If the seller's auction house has no upcoming sales,
no schedules are returned.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

