=head1 eBay::API::XML::Call::GetSuggestedCategories::GetSuggestedCategoriesResponseType

eBay::API::XML::Call::GetSuggestedCategories::GetSuggestedCategoriesResponseType

=head1 DESCRIPTION

Returns a list of categories with the highest number
of listings whose titles or descriptions contain the keywords
specified in a GetSuggestedCategoriesRequest.



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setCategoryCount()

Indicates the number of categories in the array.

#    Argument: 'xs:int'


=cut

=head2 getCategoryCount()

  Returned: Always
#    Returns: 'xs:int'


=cut

=head2 setSuggestedCategoryArray()

Contains the categories that contain listings
that match the query string in the request. The array
can have up to 10 categories. Not returned if no categories match
the query in the request.

#    Argument: 'ns:SuggestedCategoryArrayType'


=cut

=head2 getSuggestedCategoryArray()

  Returned: Conditionally
#    Returns: 'ns:SuggestedCategoryArrayType'


=cut

