=head1 NAME

eBay::API::XML::Call::GetSuggestedCategories::GetSuggestedCategoriesRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetSuggestedCategories::GetSuggestedCategoriesRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Requests a list of up to 10 categories with
the highest percentage of listings whose titles or descriptions
contain the keywords you specify.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setQuery()

Specifies the search string, consisting of one or
more words to search for in the listing title.
The words "and" and "or" are treated like any other
word.

MaxLength: 350 (characters)

  RequiredInput: Yes
#    Argument: 'xs:string'


=cut

=head2 getQuery()

#    Returns: 'xs:string'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

