=head1 eBay::API::XML::Call::SetTaxTable::SetTaxTableRequestType

eBay::API::XML::Call::SetTaxTable::SetTaxTableRequestType

=head1 DESCRIPTION

Sets the tax table for a seller on a given site.



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setTaxTable()

A container of tax jurisdiction information unique to a user/site combination.

  RequiredInput: Yes
#    Argument: 'ns:TaxTableType'


=cut

=head2 getTaxTable()

#    Returns: 'ns:TaxTableType'


=cut

