=head1 NAME

eBay::API::XML::Call::GetRuName::GetRuNameResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetRuName::GetRuNameResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Contains the generated runame (unique identifier for an authentication data entry).



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setRuName()

The generated globally unique runame.

#    Argument: 'xs:string'


=cut

=head2 getRuName()

  Returned: Always
#    Returns: 'xs:string'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

