=head1 NAME

eBay::API::XML::Call::GetApiAccessRules::GetApiAccessRulesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetApiAccessRules::GetApiAccessRulesResponseType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Responds to a call to GetApiAccessRules.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setApiAccessRule()

Contains the description of an API access rule, including the
call name, the application's current daily and hourly usage,
and other values.

#    Argument: reference to an array  
                      of 'ns:ApiAccessRuleType'


=cut

=head2 getApiAccessRule()

  Returned: Always
#    Returns: reference to an array  
                      of 'ns:ApiAccessRuleType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

