=head1 NAME

eBay::API::XML::Call::SetPictureManagerDetails::SetPictureManagerDetailsRequestType

=head1 DESCRIPTION

Creates, updates, or deletes Picture Manager account settings, folders, or pictures.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setAction()

Specifies the action to take on the setting, folder, or picture.
The values Add and Delete apply only to folders.

  RequiredInput: Yes
#    Argument: 'ns:PictureManagerActionCodeType'


=cut

=head2 getAction()

#    Returns: 'ns:PictureManagerActionCodeType'


=cut

=head2 setPictureManagerDetails()

Specifies the setting or folder to create, update, or delete, or the
picture to update. You cannot upload or delete pictures using
SetPictureManagerDetails; you must use the eBay site.

  RequiredInput: Yes
#    Argument: 'ns:PictureManagerDetailsType'


=cut

=head2 getPictureManagerDetails()

#    Returns: 'ns:PictureManagerDetailsType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

