=head1 NAME

eBay::API::XML::Call::LeaveFeedback::LeaveFeedbackResponseType

=head1 DESCRIPTION

LeaveFeedback response message includes an acknowledgement if the
feedback was successfully left.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setFeedbackID()

The ID of the feedback that has been left.

#    Argument: 'xs:string'


=cut

=head2 getFeedbackID()

  Returned: Always
#    Returns: 'xs:string'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

