=head1 NAME

eBay::API::XML::Call::VerifyAddSecondChanceItem::VerifyAddSecondChanceItemResponseType

=head1 INTERITANCE

eBay::API::XML::Call::VerifyAddSecondChanceItem::VerifyAddSecondChanceItemResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

VerifyAddSecondChanceItem request to emulate creation of a new Second Chance Offer for an item to one of
that item's bidders.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setEndTime()

Indicates the date and time when the second
chance offer listing expires, at which time
the listing ends (if the recipient user does
not purchase the item first).

#    Argument: 'xs:dateTime'


=cut

=head2 getEndTime()

  Returned: Always
#    Returns: 'xs:dateTime'


=cut

=head2 setStartTime()

Indicates the date and time when the the new
second chance offer listing became active and
the recipient user could purchase the item.

#    Argument: 'xs:dateTime'


=cut

=head2 getStartTime()

  Returned: Always
#    Returns: 'xs:dateTime'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

