=head1 eBay::API::XML::Call::AddToWatchList::AddToWatchListResponseType

eBay::API::XML::Call::AddToWatchList::AddToWatchListResponseType

=head1 DESCRIPTION



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setWatchListCount()

The number of items in the user's watch list (after those specified
in the call request have been added)

#    Argument: 'xs:int'


=cut

=head2 getWatchListCount()

  Returned: Always
#    Returns: 'xs:int'


=cut

=head2 setWatchListMaximum()

The maximum number of items allowed in watch lists. Currently this
value is the same for all sites and all users.

#    Argument: 'xs:int'


=cut

=head2 getWatchListMaximum()

  Returned: Always
#    Returns: 'xs:int'


=cut

