=head1 NAME

eBay::API::XML::Call::DeleteMyMessages::DeleteMyMessagesResponseType

=head1 DESCRIPTION

The response to DeleteMyMessagesRequestType. If the request was successful, 
DeleteMyMessages returns nothing.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

