=head1 NAME

eBay::API::XML::Call::GetDispute::GetDisputeResponseType

=head1 DESCRIPTION

Returned after calling GetDisputeRequest. Returns the record of
a dispute, including the dispute state and other information.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setDispute()

The dispute record, containing information about
the buyer, seller, dispute state, dispute status,
comments added to the dispute, or resolutions.

#    Argument: 'ns:DisputeType'


=cut

=head2 getDispute()

  Returned: Always
#    Returns: 'ns:DisputeType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

