=head1 NAME

eBay::API::XML::Call::GetDispute::GetDisputeRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetDispute::GetDisputeRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Requests the details of a dispute corresponding to the given dispute ID, any time
after the dispute was opened and up to five years after it was closed. Can be used
with Unpaid Item or Item Not Received disputes.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setDisputeID()

The unique identifier of the dispute, returned when the dispute is created.

  RequiredInput: Yes
#    Argument: 'ns:DisputeIDType'


=cut

=head2 getDisputeID()

#    Returns: 'ns:DisputeIDType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

