=head1 NAME

eBay::API::XML::Call::RespondToFeedback::RespondToFeedbackResponseType

=head1 INTERITANCE

eBay::API::XML::Call::RespondToFeedback::RespondToFeedbackResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Indicates the success or failure of the attempt to reply
to feedback that has been left for a user, or to post a
follow-up comment to a feedback comment a user has left
for someone else.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

