=head1 NAME

eBay::API::XML::Call::GeteBayOfficialTime::GeteBayOfficialTimeResponseType

=head1 DESCRIPTION

The Timestamp field indicates the official eBay system time in GMT.
For information about converting between GMT and other time zones,
see "Time Values" in the Data Types appendix in the eBay Web Services guide.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

