=head1 eBay::API::XML::Call::SetCart::SetCartResponseType

eBay::API::XML::Call::SetCart::SetCartResponseType

=head1 DESCRIPTION

The response to a call to SetCart.



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setCart()

Details about the cart.

#    Argument: 'ns:CartType'


=cut

=head2 getCart()

  Returned: Always
#    Returns: 'ns:CartType'


=cut

