=head1 NAME

eBay::API::XML::Call::GetPromotionRules::GetPromotionRulesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetPromotionRules::GetPromotionRulesResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Returns all promotion rules associated with the specified item or store category.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setPromotionRuleArray()

An array of promotion rules associated with the item or store category
specified in the request.

#    Argument: 'ns:PromotionRuleArrayType'


=cut

=head2 getPromotionRuleArray()

  Returned: Always
#    Returns: 'ns:PromotionRuleArrayType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

