=head1 NAME

eBay::API::XML::Call::SetStoreCustomPage::SetStoreCustomPageRequestType

=head1 DESCRIPTION

Sets a custom page for a user's eBay Store. The page can include static HTML
content as well as dynamic content that is added using the special eBay Stores
tags.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setCustomPage()

The custom page being submitted.

  RequiredInput: Yes
#    Argument: 'ns:StoreCustomPageType'


=cut

=head2 getCustomPage()

#    Returns: 'ns:StoreCustomPageType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

