=head1 NAME

eBay::API::XML::Call::GetTokenStatus::GetTokenStatusResponseType

=head1 DESCRIPTION

Returns token status.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setTokenStatus()

Returns token status and details. For example, if revoked, whether by eBay, the user, or the application, and also when revoked.

#    Argument: 'ns:TokenStatusType'


=cut

=head2 getTokenStatus()

  Returned: Always
#    Returns: 'ns:TokenStatusType'


=cut

=head1 SEE ALSO

L<eBay::API>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

