=head1 NAME

eBay::API::XML::Call::GetMessagePreferences::GetMessagePreferencesResponseType

=head1 INTERITANCE

eBay::API::XML::Call::GetMessagePreferences::GetMessagePreferencesResponseType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Contains the ASQ subjects for the user specified in the request.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setASQPreferences()

Returns a seller's ASQ subjects, each in its own Subject
node. If the seller has not customized the ASQ subjects
using SetMessagePreferences, the call will return the
current default values. Returned if
IncludeASQPreferences = true was specified in the
request.

#    Argument: 'ns:ASQPreferencesType'


=cut

=head2 getASQPreferences()

  Returned: Conditionally
#    Returns: 'ns:ASQPreferencesType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

