=head1 NAME

eBay::API::XML::Call::GetMessagePreferences::GetMessagePreferencesRequestType

=head1 INTERITANCE

eBay::API::XML::Call::GetMessagePreferences::GetMessagePreferencesRequestType inherits from the L<eBay::API::BaseCall> class

=head1 DESCRIPTION

Returns a seller's Ask Seller a Question (ASQ) subjects, each in
its own Subject node. If the seller has not customized the ASQ
subjects using SetMessagePreferences, the call will return the
current default values.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setIncludeASQPreferences()

If true, indicates that the ASQ subjects for the
specified user should be returned.

  RequiredInput: No
#    Argument: 'xs:boolean'


=cut

=head2 isIncludeASQPreferences()

#    Returns: 'xs:boolean'


=cut

=head2 setSellerID()

The ID of the user to retrieve ASQ subjects for. This
value must be specified in the request, but does not
need to be the same user as the user making the
request.

  RequiredInput: Yes
#    Argument: 'ns:UserIDType'


=cut

=head2 getSellerID()

#    Returns: 'ns:UserIDType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

