=head1 eBay::API::XML::Call::AddMemberMessageRTQ::AddMemberMessageRTQRequestType

eBay::API::XML::Call::AddMemberMessageRTQ::AddMemberMessageRTQRequestType

=head1 DESCRIPTION

Enables a seller to reply to a question about an active item listing.



=head1 SYNOPSIS


=cut

=head1 Subroutines:


=cut

=head2 setItemID()

The unique ID of the item about which
the question was asked.

  RequiredInput: Yes
#    Argument: 'ns:ItemIDType'


=cut

=head2 getItemID()

#    Returns: 'ns:ItemIDType'


=cut

=head2 setMemberMessage()

The message itself.

  RequiredInput: Yes
#    Argument: 'ns:MemberMessageType'


=cut

=head2 getMemberMessage()

#    Returns: 'ns:MemberMessageType'


=cut

