=head1 NAME

eBay::API::XML::Call::AddMemberMessageAAQToPartner::AddMemberMessageAAQToPartnerRequestType

=head1 INTERITANCE

eBay::API::XML::Call::AddMemberMessageAAQToPartner::AddMemberMessageAAQToPartnerRequestType inherits from the L<eBay::API::XML::BaseCall> class

=head1 DESCRIPTION

Enables a buyer and seller in a transactional relationship to send messages to each other
within 90 days of the creation of the transaction.



=head1 SYNOPSIS


=cut

=head1 Methods


=cut

=head2 setItemID()

The unique ID of the item about which the question was asked.

  RequiredInput: Yes
#    Argument: 'ns:ItemIDType'


=cut

=head2 getItemID()

#    Returns: 'ns:ItemIDType'


=cut

=head2 setMemberMessage()

The message itself.

  RequiredInput: Yes
#    Argument: 'ns:MemberMessageType'


=cut

=head2 getMemberMessage()

#    Returns: 'ns:MemberMessageType'


=cut

=head1 SEE ALSO

L<eBay::API>, L<eBay::API::XML::BaseCall>

=head1 JOIN US

Please visit http://developer.ebay.com for more eBay API information. 

Web:
L<http://developer.ebay.com>

Community Forums:
L<http://developer.ebay.com/community/forums/>

=cut

